version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fixdrive_postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: