apiVersion: apps/v1
kind: Deployment
metadata:
  name: fixdrive-app
  namespace: fixdrive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fixdrive-app
  template:
    metadata:
      labels:
        app: fixdrive-app
    spec:
      containers:
      - name: fixdrive-app
        image: fixdrive:latest  # Замени на свой image
        imagePullPolicy: Never  # Используем локальный образ
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: fixdrive-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: fixdrive-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: fixdrive-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: fixdrive-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fixdrive-secret
              key: DB_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: fixdrive-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: fixdrive-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: fixdrive-config
              key: REDIS_PASSWORD
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: fixdrive-config
              key: REDIS_DB
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: fixdrive-config
              key: PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: fixdrive-secret
              key: JWT_SECRET
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: fixdrive-secret
              key: TWILIO_ACCOUNT_SID
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: fixdrive-secret
              key: TWILIO_AUTH_TOKEN
        - name: TWILIO_FROM_PHONE
          valueFrom:
            secretKeyRef:
              name: fixdrive-secret
              key: TWILIO_FROM_PHONE
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: fixdrive-app
  namespace: fixdrive
spec:
  selector:
    app: fixdrive-app
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 