apiVersion: v1
kind: Secret
metadata:
  name: fixdrive-secret
  namespace: fixdrive
type: Opaque
data:
  # password в base64
  DB_PASSWORD: cGFzc3dvcmQ=
  # your-super-secret-jwt-key-change-in-production в base64
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  # Твои Twilio данные в base64
  TWILIO_ACCOUNT_SID: QUM5MzkzZDYwYjM1ZjZlNjk1NmFlNWZlMDZkZjc4N2U3Zg==
  TWILIO_AUTH_TOKEN: YmUyY2Q2MWRlNDRhMzliNzI0YWYyZDFkNjAzODNjZTE=
  TWILIO_FROM_PHONE: KzE1MTU3MTU0MDUx 